In [4]:
import numpy as np

In [5]:
# Q1_0111. 아래 배열에 제곱한 경우와 제곱근의 경우를 계산하여 출력하세요
array = np.array([1,2,3,4])

In [6]:
print(array ** 2)
np.sqrt(array)

[ 1  4  9 16]

array([1.        , 1.41421356, 1.73205081, 2.        ])

Q2_0111. ar에 reshape() 함수 이용, 1차원, 2차원 , 3차원 배열을 만드시오

In [7]:
arr4 = np.arange(12)

arr5 = arr4.reshape(2,6)

arr6 = arr5.reshape(2,3,2)

print(arr4, '\n')
print(arr5, '\n')
print(arr6, '\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

In [8]:
arr_1d = np.arange(6)
arr_2d = arr_1d.reshape(2, 3)
arr_3d = arr_1d.reshape(2, 3, 1)
print(arr_1d, '\n')
print(arr_2d, '\n')
print(arr_3d, '\n')

[0 1 2 3 4 5]

[[0 1 2]
 [3 4 5]]

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]

Q3_0111. 1차원 배열을 생성한 후 -1을 이용해서 차원을 변경해 보세요
- 1차원 -> 2,3차원
- 2차원 -> 1,3차원
- 3차원 -. 1,2차원

In [9]:
# -1 을 쓰면 알아서 계산 해줌

arrq3 = np.arange(18)
arrq32 = arrq3.reshape(2,-1)
arrq33 = arrq3.reshape(3,2,-1)
print(arrq3, '\n')
print(arrq32, '\n')
print(arrq33, '\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]

In [11]:
arrq34 = arrq32.reshape(-1,)
arrq35 = arrq32.reshape(3,2,-1)
print(arrq34, '\n')
print(arrq35, '\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]

In [12]:
arrq36 = arrq33.reshape(-1,)
arrq37 = arrq33.reshape(2,-1)
print(arrq36, '\n')
print(arrq37, '\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]

Q4_0111. 1차원 배열을 생성 후 2,3차 배열로 변경하고 각 2,3차원 배열을 1,3차원, 1,2차원 배열로 다시 변경해서 출력하세요.

In [13]:
ar =  np.arange(24)
ar12 = ar.reshape(2,-1)
ar13 = ar.reshape(3,4,-1)

ar21 = ar12.reshape(-1,)
ar23 = ar12.reshape(3,2,-1)

ar31 = ar13.reshape(-1,)
ar32 = ar13.reshape(6,-1)

print(ar, '\n')
print(ar12, '\n')
print(ar13, '\n')

print(ar12, '\n')
print(ar21, '\n')
print(ar23, '\n')

print(ar13, '\n')
print(ar31, '\n')
print(ar32, '\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Q5_0111. 1차원 배열을 생성하여 2차원 배열로 변환한 후 다음 사항을 수행하세요
- 2차원 배열을 리스트로 타입 변경하세요
- 리스트를 다시 배열로 변경하세요

In [17]:
ar = np.arange(16)
print(ar, '\n')
ar2d = ar.reshape(2,8)
print(ar2d, '\n', type(ar2d), '\n')
li = ar2d.tolist()
print(li, '\n', type(li), '\n')
array2 =  np.array(li)
print(array2, '\n', type(array2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
 <class 'numpy.ndarray'>

[[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14, 15]]
 <class 'list'>

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
 <class 'numpy.ndarray'>

Q6_0111. 두 배열 [[1,2],[3,4]]와 [[5,6],[7,8]]를 가로로 연결하기

In [14]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
concatenated = np.concatenate((a,b), axis=1)
print(concatenated, '\n')

[[1 2 5 6]
 [3 4 7 8]]

Q7_0111. 두 배열 [[1,2,3]]와 [[4,5,6]]을 세로로 연결하기

In [15]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
concatenated = np.concatenate((a,b), axis=0)
stacked = np.vstack((a,b))
print(concatenated, '\n')
print(stacked)

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]

Q8_0111. 배열 [0,1,2,3,4,5,6,7,8]를 세 부분으로 나누기

In [16]:
a = np.array([0,1,2,3,4,5,6,7,8])
split1, split2, split3 = np.split(a,3)
print(split1, "\n", split2, '\n', split3)

[0 1 2]
 [3 4 5]
 [6 7 8]

In [ ]:
# Q9_0111. array2d에서 슬라이싱을 사용해서 아래와 같이 출력하세요.
[[1 2]
[4 5]]

(2가지 방법)
[[4 5 6]
[7 8 9]]

[[1 2 3]
[4 5 6]
[7 8 9]]

[[2 3]
[5 6]]

[1 4]

In [19]:
array2d = np.arange(1,10).reshape(3,3)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
array2d[:2,0:2]

array([[1, 2],
       [4, 5]])

In [21]:
array2d[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [22]:
array2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
# Q10_0111. 1~14까지 ndarray를 만들어 array_e로 저장하고 (array_e / 2) > 5를 만족하는 값을 불린 인덱스로 출력하세요

In [23]:
array_e = np.arange(1,15)
arrayq10 = array_e[array_e / 2 > 5]
print(arrayq10)

[11 12 13 14]

In [ ]:
#Q11_0111. 1~100까지 정수에서 5의 배수이면서 2의 배수인 것만을 출력(for문과 배열 두 가지 방식)

In [24]:
array_f = np.arange(1,101)
arrayq11 = array_f[(array_f % 5 == 0) & (array_f % 2 == 0)]
print(arrayq11)

[ 10  20  30  40  50  60  70  80  90 100]

In [25]:
array_f = np.arange(1, 101)
arrayq11 = []

for num in array_f:
    if num % 5 == 0 and num % 2 == 0:
        arrayq11.append(num)

arrayq11 = np.array(arrayq11)
print(arrayq11)

[ 10  20  30  40  50  60  70  80  90 100]

In [ ]:
# Q12_0111. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하세요

In [26]:
arrayq12 = np.random.randn(5, 5)
arrm = arrayq12.mean()
arrstd = arrayq12.std()
print(arrayq12, '\n')
print(arrm, '\n')
print(arrstd)

[[-0.56435791  0.01868148  0.76212411 -0.33666634  1.35820337]
 [ 2.4564139  -1.16066288  1.68455753 -0.663344    1.40329762]
 [ 0.59835001  0.68665761  1.67601551  0.46312476 -1.54623773]
 [ 1.0793267   0.65833966 -1.947017    0.37138861  1.45021993]
 [-1.05765508  0.62821164  1.3694674  -1.07810981 -1.04893543]]

0.2904557457680077

1.1472094235136336